### PR TITLE
Style fix

### PR DESCRIPTION
**Pull request by alldne**
I guess our travis is currently broken. Let's fix it next sprint

### CODE REVIEW

**Comment by jackxujh** [comment]
I filed a bug #73  on this exact issue earlier yesterday. I am okay if we fix this, but I would prefer to have the hardware team fix this, and test their CI configs, as they have the best knowledge on the module.

**Comment by alldne** [comment]
@jackxujh  Next time please just ping and ask me you want to close it before actually closing an issue.

**Comment by jackxujh** [comment]
@alldne sure, I will send you a message and not do any actions. I was just not sure if any body is going to merge this PR at that moment, given it was already surprisingly approved.

**Comment by alldne** [comment]
No worries. Since this pr was to fix the build issue and currently the issue seems to be fixed, I'll close this

**Pull request closed without merging**
