### PR TITLE
Frontend team

### PR DESCRIPTION
**Pull request by daisycrego**

### CODE REVIEW

**Comment by alldne** [comment]
This branch is out-of-date with the base branch

**Comment by alldne** [comment]
@sunnybansal Please do not approve a PR into master unless you're oncall this sprint.

Approving a PR into master is responsibility of oncall member. If master is broken, oncall needs to fix it. That's why all the PR into master should get an approval from oncall.

Since the minimum number of approval on our repo is one, if you approve this pr, anyone can merge it after you approved. And oncall gets to lose control

**Comment by sunnybansal** [comment]
Yes @alldne, I will take a note of this. We are trying to put all the things together for today's demo from all teams. Will make sure to loop you in or the person in call going forward.
Thanks

**Comment by daisycrego** [comment]
@alldne coverage only decreased because we merged master on this branch first

**Pull request merged**
